databases.resort360.folder.1\ -\ dataconnection.folder.2\ -\ base\ views.views.jdbc.bv_supplier.CATALOGNAME=Resort360DB
databases.resort360.folder.1\ -\ dataconnection.folder.2\ -\ base\ views.views.jdbc.bv_supplier.SCHEMANAME=dbo
