databases.resort360.folder.6\ -\ summaries.views.jdbc.summ_room_category_revenue.CATALOGNAME=Resort360_DS
databases.resort360.folder.6\ -\ summaries.views.jdbc.summ_room_category_revenue.SCHEMANAME=dbo
