databases.resort360.webcontainer.webservices.ws_bookings_details.LOGIN=admin
databases.resort360.webcontainer.webservices.ws_bookings_details.PASSWORD=quJnyhn9tO28JyCskmpgc6r2LZ8mGDpMWxeC/2LH8ad6NnPmpRoFWMVNVBTRB8wYBfUn0KxrAcX0v9km9wZtUIVqZPaNQeyMCqzP32BeeWzPq8WrtU/cnSCDOM7P6qGv
databases.resort360.webcontainer.webservices.ws_bookings_details.PASSWORD.ENCRYPTED=ENCRYPTED
