databases.resort360.webcontainer.webservices.ws_product_details.LOGIN=admin
databases.resort360.webcontainer.webservices.ws_product_details.PASSWORD=GugCa7DKy77Y8fwl9uuyn/NjfMVI+KOxODqr/TaCaAsP/WTnVGDsQldoUMcVyJLp0sX3zpdPN4n6iuzA/813gbxWrpssr2sb/XfU+JEOgF4xx/oXJjCFTcBC9c2JIB88
databases.resort360.webcontainer.webservices.ws_product_details.PASSWORD.ENCRYPTED=ENCRYPTED
